### PR TITLE
Update __init__.py

### LINKED ISSUE #6: Unhandled type of video in snaps
There is a type of video that isn't handled by the tool, currently throws an error when queried.

### PR DESCRIPTION
**Pull request by AlanTheBlank**
There was a type of video that was breaking the tool, this will filter it out

### CODE REVIEW

**Comment by king-millez** [comment]
I'd rather download the video than just ignore it, can you give me an example of what the API data shows when that snap is queried?

**Comment by AlanTheBlank** [comment]
so actually looking into it, it gets weirder.  it's almost like it's a ghost entry of sorts.  Here is the json data for a entry that throws the issue, there is no media url in it to pull it which is why I opted to ignore it in the pull request.
`{
'id': 'W7_EDlXWTBiXAEEniNoMPwAAYZ_IaiK4im-6fAXlHOctIAXlHOcoRAO1OAA', 
'duration': 6.498888888888889, 
'timestamp': '1620397563000', 
'snapInfo': {
'snapMediaType': 'SNAP_MEDIA_TYPE_VIDEO', 
'title': {
'strings': [
{'locale': 'zh', 'text': '都柏林, 爱尔兰岛'}, 
{'locale': 'fr', 'text': 'Dublin, Irlande (île)'}, 
{'locale': 'pt', 'text': 'Dublim, Irlanda'}, 
{'locale': 'ko', 'text': '더블린, 아일랜드 섬'}, 
{'locale': 'en', 'text': 'Dublin, Ireland'}, 
{'locale': 'de', 'text': 'Dublin, Irland (Insel)'}, 
{'locale': 'ar', 'text': 'دبلن, جزيرة أيرلندا'}, 
{'locale': 'ja', 'text': 'ダブリン, アイルランド島'}, 
{'locale': 'ru', 'text': 'Дублин, Ирландия (остров)'}, 
{'locale': 'es', 'text': 'Dublín, Irlanda'}], 
'fallback': 'Dublin, Ireland'
}, 
'streamingMediaInfo': {}
}
}
`
To replicate this, I searched 10km around roughly 53.350842,-6.260168

**Comment by king-millez** [comment]
The thing that's really weird to me is that the API says that snap has a set duration...

**Comment by king-millez** [comment]
I just found a similar error where the video is missing, but the MP4 thumbnail is perfectly valid:

Did your snap have no thumbnail entries?

```json
{
  "id": "W7_EDlXWTBiXAEEniNoMPwAAYJeLFDZ1TuACYAXlJfbVRAXlJfbRXAO1OAA",
  "duration": 9.53,
  "timestamp": "1620435325000",
  "snapInfo": {
    "snapMediaType": "SNAP_MEDIA_TYPE_VIDEO",
    "title": {
      "strings": [
        {
          "locale": "ko",
          "text": "Edmondson Park, \ub274\uc0ac\uc6b0\uc2a4\uc6e8\uc77c\uc2a4 \uc8fc"
        },
        {
          "locale": "ru",
          "text": "Edmondson Park, \u041d\u043e\u0432\u044b\u0439 \u042e\u0436\u043d\u044b\u0439 \u0423\u044d\u043b\u044c\u0441"
        },
        {
          "locale": "ar",
          "text": "Edmondson Park, \u0646\u064a\u0648\u0633\u0627\u0648\u062b \u0648\u064a\u0644\u0632"
        },
        {
          "locale": "de",
          "text": "Edmondson Park, New South Wales"
        },
        {
          "locale": "es",
          "text": "Edmondson Park, Nueva Gales del Sur"
        },
        {
          "locale": "fr",
          "text": "Edmondson Park, Nouvelle-Galles du Sud"
        },
        {
          "locale": "en",
          "text": "Edmondson Park, New South Wales State"
        },
        {
          "locale": "ja",
          "text": "Edmondson Park, \u30cb\u30e5\u30fc\u30b5\u30a6\u30b9\u30a6\u30a7\u30fc\u30eb\u30ba\u5dde"
        },
        {
          "locale": "zh",
          "text": "Edmondson Park, \u65b0\u5357\u5a01\u723e\u58eb\u5dde"
        },
        {
          "locale": "pt",
          "text": "Edmondson Park, Nova Gales do Sul"
        }
      ],
      "fallback": "Edmondson Park, New South Wales State"
    },
    "streamingMediaInfo": {},
    "streamingThumbnailInfo": {
      "infos": [
        {
          "thumbnailType": "IMAGE_THUMBNAIL_TYPE",
          "thumbnailUrl": "https://s.sc-cdn.net/T_Kn8YSbxfWVAW19dDPh259JOR3feUPrXA-N1lw3Jg0=/default/thumb/thumb.jpg"
        },
        {
          "thumbnailType": "VIDEO_THUMBNAIL_TYPE",
          "thumbnailUrl": "https://s.sc-cdn.net/T_Kn8YSbxfWVAW19dDPh259JOR3feUPrXA-N1lw3Jg0=/default/thumb/thumb.mp4"
        }
      ]
    }
  }
}
```

**Comment by AlanTheBlank** [comment]
I posted all that was in the snapInfo section.  It could be an issue with snapmap on snapchat's end.

**Comment by AlanTheBlank** [comment]
Closing the pull request because I am happy the recent commit has fixed the issue and is 100x better than my band-aid fix.  Would it be possible to get that update pushed to the pypi project page?

**Pull request closed without merging**
